# Generated by Django 4.2.7 on 2024-01-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gentlelink", "0002_alter_tasks_deadline_alter_tasks_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memos",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gentlelink.calendars",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="calendar_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="font_style",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
