# Generated by Django 4.2.7 on 2024-01-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gentlelink", "0003_alter_memos_calendar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="calendar_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="font_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
