# Generated by Django 4.2.7 on 2024-01-17 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gentlelink", "0006_rename_taskshare_taskshares"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoupleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "husband",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_user_husband",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wife",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couple_user_wife",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
